[package]
name = "poly"
version = "0.1.0"
edition = "2021"
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

[[bin]]
name = "parser_benchmark"
path = "benches/parser_benchmark.rs"
